# TODO:
# read a csv file from the output step and read the termination and decide to rerun the job (or not?)
#



def find_faulty(csv: str) -> n: int:
    """ 
    returns n (number of failures)
    """

    pass


